language: cpp

script:
  - ./autogen.sh
  - ./configure --prefix=$PWD/_inst
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi

matrix:
  include:
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    dist: precise
  - os: linux
    services: docker
    env: DOCKER_TAG=ubuntu:16.04 OS_TAG=ubuntu-16.04 
  - os: osx
    before_install:
      - brew update
      - brew install lzo docbook2x

before_install:
  - if [[ -n "$DOCKER_TAG" ]]; then docker pull ${DOCKER_TAG} && docker run ${DOCKER_TAG} bash ./autogen.sh \; ./configure --prefix=$PWD/_inst \; make \; make test ; fi


addons:
  apt:
    packages:
    - libcap-ng-dev
    - libcap-ng-utils
    - liblzo2-dev
    - docbook2x
    - realpath
